version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: ussp_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ussp_db
      MYSQL_ROOT_PASSWORD: root_pass
    volumes:
      - db_data:/var/lib/mysql

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: ussp_server
    ports:
      - "8000:8000"
    volumes:
      - ./server:/var/www/html
    environment:
      - DB_HOST=db
    depends_on:
      - db

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: ussp_client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules # prevents local node_modules from overwriting container's

volumes:
  db_data: